# Generated by Django 3.2.5 on 2022-04-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scene',
            new_name='Quest',
        ),
    ]
