# Generated by Django 3.2.5 on 2022-04-15 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_scene_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
