# Generated by Django 3.2.5 on 2022-04-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_device_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
