# Generated by Django 3.2.5 on 2022-04-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_device_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
