# Generated by Django 3.2.5 on 2022-04-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20220415_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='scene',
            new_name='task',
        ),
    ]
