# Generated by Django 3.2.5 on 2022-04-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20220419_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
