# Generated by Django 3.2.5 on 2022-04-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_face_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
