# Generated by Django 3.2.5 on 2022-04-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_face_face_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='task',
        ),
        migrations.AddField(
            model_name='event',
            name='task_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='task_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
